### ISSUE TITLE
Car device not updating

### ISSUE THREAD

**Issue by turribeach** [FlyingDiver/Indigo-Connected-Drive#10]
Hi, I have updated to version 2022.0.0 running under Indigo 2022.1. Initially I thought the car device was not updating properly but I think there is something else going as well. I have set the plugin update frecuency to 5 mins. I see the debug logging messages on the logs every 5 mins and there are no errors shown. If I look at the car device in the Indigo MacOS client now I see this:

![image](https://user-images.githubusercontent.com/34696469/168232789-64f1114a-488f-4a9c-9448-ee8e2dc7f7f6.png)

It's currently 8:25am here so obviously way out of date. But interestingly if I look at the car device in the Indigo iOS App I see this:

![image](https://user-images.githubusercontent.com/34696469/168233183-466cd9c7-42c1-4597-b675-70d2a0cebb12.png)

This is still an hour older than current time but I don't understand why it doesn't match the device Last Update in the MacOS app. Finally if I do "Print Device Details to Event Log" over the car device in the Indigo MacOS app I get these:

lastChanged : 2022-05-13 08:25:23
lastSuccessfulComm : 2022-05-13 08:25:23

Which it doesn't match the device Last Update in the MacOS app nor the one in iOS. So I am really confused now.... :-) 

One final minor issue is that if I select About Connected drive in the Indigo MacOS client => Plugins nothing happens. Usually this option takes you to the plugin Indigo forums page or the Github repo.

**Comment by turribeach** [comment]
One thing worth mentioning is that none of the above date/times have anything to do (as expected) with the last time the car itself updated it's status (ie when was the last time the car was locked). This is reporting correctly under the timestamp device property (albeit it being in UTC rather than my local time zome) and it's matching what the BMW official app shows.

**Comment by FlyingDiver** [comment]
The plugin has no control over any of those fields.  That's all Indigo server and client.  If this is repeatable, it should be reported to the Indigo team.

**Comment by turribeach** [comment]
I think the issue here is the same as #9 and #11, since nothing is changing the Indigo device then Indigo is not updating the device date/Time. So really the solution to these 3 issues is to simple have a date/time field on the device which gets updated every time the plugin fetches new data form the BMW API, whether it's the same data or not is irrelevant. That way we can fire triggers every time the plugin runs.
