### ISSUE TITLE
Add Last Update to list of fields you can use in a trigger

### ISSUE THREAD

**Issue by turribeach** [FlyingDiver/Indigo-Connected-Drive#11]
Please add Device Last UpdateDate/Time to list of fields you can use in a trigger for the Car Device. The idea behind it is to to log events when the car device has been updated. Thanks!

**Comment by FlyingDiver** [comment]
Why not use timestamp?

**Comment by turribeach** [comment]
timestamp is when the car was last updated which is not the same as Device Last Update. For instance Device Last Update can change while timestamp doesn't (when the car is parked and the Indigo device is "refreshed"). I rather know the device was updated but the car has not.

**Comment by FlyingDiver** [comment]
Can you give me an example of what you would use that trigger for?

**Comment by turribeach** [comment]
I want to log all the details of the car every time I can so I can have a full audit trail.

**Comment by FlyingDiver** [comment]
For now, I suggest using a schedule to do that.  I'll look into adding another state field when I get data for PEV and Hybrid vehicles and update the state lists for those.

**Comment by ryanbuckner** [comment]
From what I can see, the timestamp field represents the last time the BMW API updated information about the car, and Last Update represents the last time the Indigo device was updated.  I was driving (stopped at a light) when I took these screenshots at 12:22PM EST and my car doors were locked. The information had not been collected in 30 minutes but the Indigo API calls happen every 5 minutes. 

@turribeach I think you can use the timestamp for your trigger use case

![car1](https://user-images.githubusercontent.com/1781929/168483492-30f8c433-2f70-4c66-b1af-9a4719581106.PNG)
![car2](https://user-images.githubusercontent.com/1781929/168483493-a81508e3-2b01-4ce7-b5ef-625e38d9e90b.PNG)

**Comment by turribeach** [comment]
The BMW API is a but crap, it used to update a lot more frequently but now it has reduced the frequency. I am guessing BMW tweaked the frequency the car sends updates or they have changed their logic so that certain things don't trigger an update to save costs since the updates are "pushed" by the car using a SIM that's paid by BMW. I have also long suspected the code that sends updates is not very clever nor handles errors very well. For instance if you are in an area of low / no cell signal it will obviously not update but when you come out of that area it will take a while to update, even if you are in an area you know the car can get good reception as you had updates from that area before. Using timestamp won't cover all my use cases, but will do for now.

**Comment by ryanbuckner** [comment]
Agreed. I think you can close this request.  Not much that the plugin can do to improve this need.

**Comment by turribeach** [comment]
There is one thing, which is allow the Device Last Update to be selected as a field in the trigger.

**Comment by ryanbuckner** [comment]
ok then yes. A new device state would need to be created for that.

**Comment by FlyingDiver** [comment]
> There is one thing, which is allow the Device Last Update to be selected as a field in the trigger. 

It's not a device state, so I would need to create a state an populate it every update. And I'm just sure that actually does anything useful.

**Comment by FlyingDiver** [comment]
https://github.com/FlyingDiver/Indigo-Connected-Drive/releases/tag/2022.1.0b1

**Comment by turribeach** [comment]
Thanks! I am getting an error on my script now since timestamp lost the time zone. The new field has it though, I don't really mind either way but might be better to have both dates with time zone or without it to be consistent?

     last_update : 24 May 2022 20:38:16 BST
     timestamp : 24 May 2022 15:37:11

**Comment by turribeach** [comment]
But thew new field is working fine and it's also triggering the Indigo Device Update as it's changing the device states... :-)

**Comment by FlyingDiver** [comment]
Can you make that a new issue please.

**Comment by FlyingDiver** [comment]
IN 2022.1.X.
