### ISSUE TITLE
Bring back some car states

### ISSUE THREAD

**Issue by turribeach** [FlyingDiver/Indigo-Connected-Drive#12]
Hi,

I noticed the new plugin version is missing some car states that were present before. Here are the ones I am looking to use:

    "doorsAndWindows": {
    "doors": {
        "driverFront": "CLOSED",
        "driverRear": "CLOSED",
        "passengerFront": "CLOSED",
        "passengerRear": "CLOSED"
    },
    "hood": "CLOSED",
    "moonroof": "CLOSED",
    "trunk": "CLOSED",
    "windows": {
        "driverFront": "CLOSED",
        "driverRear": "CLOSED",
        "passengerFront": "CLOSED",
        "passengerRear": "CLOSED"
    "heading": 329

The main use for these is to check that all doors and windows are closed when the car is parked at home. I have a script that checks the geolocation and when the car is within 100mts of my home it sends an alert if the car is not locked or any window/door/sunroof/hood/trunk is open and the car has been parked for more than 15mins.

Here are others I am interested on and it will be nice to have:

    "all_lids_closed": true,
    "all_windows_closed": true,
    "are_all_cbs_ok": true,
    "open_windows": [],
    "areDoorsClosed": true,
    "areDoorsLocked": true,
    "areDoorsOpen": false,
    "areWindowsClosed": true,
    "checkControlMessages": [],
            "fuelLevel": {
                "units": "LITERS",
                "value": 37
            },
            "inMotion": false,
            "isServiceRequired": false,
            "serviceRequired": [
                {
                    "dateTime": "2023-02-01T00:00:00.000Z",
                    "distance": {
                        "units": "KILOMETERS",
                        "value": 13000
                    },
                    "status": "OK",
                    "type": "OIL"
                },
                {
                    "dateTime": "2023-02-01T00:00:00.000Z",
                    "distance": {
                        "units": "KILOMETERS",
                        "value": 13000
                    },
                    "status": "OK",
                    "type": "VEHICLE_CHECK"
                },
                {
                    "dateTime": "2024-02-01T00:00:00.000Z",
                    "status": "OK",
                    "type": "BRAKE_FLUID"
                }
            ],        
            "remaining_range_total": [
                321,
                "mi"
            ],`

Here is a full dump of my car data in case it helps:

    Connected Drive                 Data for VIN ABCD1234:
    {
        "account": 9999999999999,
        "status": {
            "all_lids_closed": true,
            "all_windows_closed": true,
            "are_all_cbs_ok": true,
            "are_parking_lights_on": null,
            "charging_end_time": null,
            "charging_level_hv": null,
            "charging_start_time": null,
            "charging_status": null,
            "charging_time_label": null,
            "charging_time_remaining": 0.0,
            "check_control_messages": [],
            "connection_status": null,
            "door_lock_state": "LOCKED",
            "fuel_indicator_count": 1,
            "fuel_percent": null,
            "gps_heading": 329,
            "gps_position": [
                99.99999,
                99.99999
            ],
            "has_check_control_messages": false,
            "has_parking_light_state": false,
            "is_vehicle_active": false,
            "last_charging_end_result": null,
            "last_update_reason": "Updated from vehicle 5/16/2022 03:27 PM",
            "max_range_electric": null,
            "mileage": [
                16938,
                "mi"
            ],
            "open_lids": [],
            "open_windows": [],
            "parking_lights": null,
            "properties": {
                "areDoorsClosed": true,
                "areDoorsLocked": true,
                "areDoorsOpen": false,
                "areWindowsClosed": true,
                "checkControlMessages": [],
                "climateControl": {},
                "combustionRange": {
                    "distance": {
                        "units": "KILOMETERS",
                        "value": 517
                    }
                },
                "doorsAndWindows": {
                    "doors": {
                        "driverFront": "CLOSED",
                        "driverRear": "CLOSED",
                        "passengerFront": "CLOSED",
                        "passengerRear": "CLOSED"
                    },
                    "hood": "CLOSED",
                    "moonroof": "CLOSED",
                    "trunk": "CLOSED",
                    "windows": {
                        "driverFront": "CLOSED",
                        "driverRear": "CLOSED",
                        "passengerFront": "CLOSED",
                        "passengerRear": "CLOSED"
                    }
                },
                "fuelLevel": {
                    "units": "LITERS",
                    "value": 37
                },
                "inMotion": false,
                "isServiceRequired": false,
                "lastUpdatedAt": "2022-05-16T14:27:51Z",
                "originCountryISO": "GB",
                "serviceRequired": [
                    {
                        "dateTime": "2023-02-01T00:00:00.000Z",
                        "distance": {
                            "units": "KILOMETERS",
                            "value": 13000
                        },
                        "status": "OK",
                        "type": "OIL"
                    },
                    {
                        "dateTime": "2023-02-01T00:00:00.000Z",
                        "distance": {
                            "units": "KILOMETERS",
                            "value": 13000
                        },
                        "status": "OK",
                        "type": "VEHICLE_CHECK"
                    },
                    {
                        "dateTime": "2024-02-01T00:00:00.000Z",
                        "status": "OK",
                        "type": "BRAKE_FLUID"
                    }
                ],
                "vehicleLocation": {
                    "address": {
                        "formatted": "xxxxx"
                    },
                    "coordinates": {
                        "latitude": 99.999,
                        "longitude": 99.999
                    },
                    "heading": 329
                }
            },
            "remaining_fuel": [
                37,
                "LITERS"
            ],
            "remaining_range_electric": [
                null,
                null
            ],
            "remaining_range_fuel": [
                321,
                "mi"
            ],
            "remaining_range_total": [
                321,
                "mi"
            ],
            "status": {
                "checkControlMessages": [
                    {
                        "criticalness": "nonCritical",
                        "iconId": 60197,
                        "state": "OK",
                        "title": "Engine Oil"
                    }
                ],
                "checkControlMessagesGeneralState": "No Issues",
                "currentMileage": {
                    "formattedMileage": "16938",
                    "mileage": 16938,
                    "units": "mi"
                },
                "doorsAndWindows": [
                    {
                        "criticalness": "nonCritical",
                        "iconId": 59757,
                        "state": "Locked",
                        "title": "Lock status"
                    },
                    {
                        "criticalness": "nonCritical",
                        "iconId": 59722,
                        "state": "Closed",
                        "title": "All doors"
                    },
                    {
                        "criticalness": "nonCritical",
                        "iconId": 59725,
                        "state": "Closed",
                        "title": "All windows"
                    },
                    {
                        "criticalness": "nonCritical",
                        "iconId": 59706,
                        "state": "Closed",
                        "title": "Hood"
                    },
                    {
                        "criticalness": "nonCritical",
                        "iconId": 59704,
                        "state": "Closed",
                        "title": "Trunk"
                    },
                    {
                        "criticalness": "nonCritical",
                        "iconId": 59705,
                        "state": "Closed",
                        "title": "Sunroof"
                    }
                ],
                "doorsGeneralState": "Locked",
                "fuelIndicators": [
                    {
                        "chargingType": null,
                        "iconOpacity": "high",
                        "infoIconId": 59930,
                        "infoLabel": "Fuel Level",
                        "isCircleIcon": false,
                        "isInaccurate": true,
                        "levelIconId": 59682,
                        "levelUnits": "l",
                        "levelValue": "37",
                        "mainBarValue": 0,
                        "rangeIconId": 59681,
                        "rangeUnits": "mi",
                        "rangeValue": "321",
                        "secondaryBarValue": 0,
                        "showsBar": false
                    }
                ],
                "issues": {},
                "lastUpdatedAt": "2022-05-16T14:27:51Z",
                "recallExternalUrl": null,
                "recallMessages": [],
                "requiredServices": [
                    {
                        "criticalness": "nonCritical",
                        "iconId": 60197,
                        "id": "Oil",
                        "longDescription": "Next service due after the specified distance or date.",
                        "subtitle": "Due in February 2023 or 8078 mi",
                        "title": "Engine oil"
                    },
                    {
                        "criticalness": "nonCritical",
                        "iconId": 60215,
                        "id": "VehicleCheck",
                        "longDescription": "Next vehicle check due after the specified distance or date.",
                        "subtitle": "Due in February 2023 or 8078 mi",
                        "title": "Vehicle check"
                    },
                    {
                        "criticalness": "nonCritical",
                        "iconId": 60223,
                        "id": "BrakeFluid",
                        "longDescription": "Next service due by the specified date.",
                        "subtitle": "Due in February 2024",
                        "title": "Brake fluid"
                    }
                ],
                "timestampMessage": "Updated from vehicle 5/16/2022 03:27 PM"
            }
        },
        "vehicle": {
            "attributes": {
                "a4aType": "BLUETOOTH",
                "bodyType": "F48",
                "brand": "BMW",
                "capabilities": {
                    "canRemoteHistoryBeDeleted": false,
                    "climateNow": {
                        "executionMessage": "Do you want to ventilate now? Remote functions may take a few seconds.",
                        "executionPopup": {
                            "executionMessage": "Do you want to ventilate now? Remote functions may take a few seconds.",
                            "iconId": 59733,
                            "popupType": "DIALOG",
                            "primaryButtonText": "Start",
                            "secondaryButtonText": "Cancel",
                            "title": "Start Ventilation"
                        },
                        "executionStopPopup": {
                            "executionMessage": "Stop climate control in your vehicle now? Remote functions may take a few seconds.",
                            "title": "Climate control is running"
                        },
                        "isEnabled": true,
                        "isPinAuthenticationRequired": false
                    },
                    "climateTimer": {
                        "isEnabled": true,
                        "isPinAuthenticationRequired": false,
                        "isToggleEnabled": true,
                        "page": {
                            "description": "By setting a start time you let the vehicle know when you plan to use it.",
                            "primaryButtonText": "SEND TO VEHICLE",
                            "secondaryButtonText": "DEACTIVATE AND SEND TO VEHICLE",
                            "subtitle": "Set start time",
                            "title": "Ventilation timer"
                        },
                        "tile": {
                            "description": "Plan start time",
                            "iconId": 59774,
                            "title": "Ventilation timer"
                        }
                    },
                    "isBmwChargingSupported": false,
                    "isCarSharingSupported": false,
                    "isChargeNowForBusinessSupported": false,
                    "isChargingHistorySupported": false,
                    "isChargingHospitalityEnabled": false,
                    "isChargingLoudnessEnable": false,
                    "isChargingPlanSupported": false,
                    "isChargingPowerLimitEnable": false,
                    "isChargingSettingsEnabled": false,
                    "isChargingTargetSocEnable": false,
                    "isCustomerEsimSupported": false,
                    "isDCSContractManagementSupported": false,
                    "isDataPrivacyEnabled": false,
                    "isEasyChargeSupported": false,
                    "isEvGoChargingSupported": false,
                    "isFindChargingEnabled": false,
                    "isMiniChargingSupported": false,
                    "isRemoteHistorySupported": true,
                    "isRemoteParkingSupported": false,
                    "isRemoteServicesActivationRequired": false,
                    "isRemoteServicesBookingRequired": false,
                    "isScanAndChargeSupported": false,
                    "isSustainabilitySupported": false,
                    "lastStateCall": {
                        "isNonLscFeatureEnabled": false,
                        "lscState": "ACTIVATED"
                    },
                    "lights": {
                        "executionMessage": "Flash headlights now? Remote functions may take a few seconds.",
                        "isEnabled": true,
                        "isPinAuthenticationRequired": false
                    },
                    "lock": {
                        "executionMessage": "Lock your vehicle now? Remote functions may take a few seconds.",
                        "isEnabled": true,
                        "isPinAuthenticationRequired": false
                    },
                    "sendPoi": {
                        "executionMessage": "Send POI now? Remote functions may take a few seconds.",
                        "isEnabled": true,
                        "isPinAuthenticationRequired": false
                    },
                    "specialThemeSupport": [],
                    "unlock": {
                        "executionMessage": "Unlock your vehicle now? Remote functions may take a few seconds.",
                        "isEnabled": true,
                        "isPinAuthenticationRequired": true
                    },
                    "vehicleFinder": {
                        "executionMessage": "Find your vehicle now? Remote functions may take a few seconds.",
                        "isEnabled": true,
                        "isPinAuthenticationRequired": false
                    }
                },
                "connectedDriveServices": [
                    "WIFI_HOTSPOT_SERVICE"
                ],
                "driveTrain": "COMBUSTION",
                "driverGuideInfo": {
                    "androidAppScheme": "com.bmwgroup.driversguide.row",
                    "androidStoreUrl": "https://play.google.com/store/apps/details?id=com.bmwgroup.driversguide.row",
                    "iosAppScheme": "bmwdriversguide:///open",
                    "iosStoreUrl": "https://apps.apple.com/de/app/id714042749?mt=8",
                    "title": "BMW\nDriver's Guide"
                },
                "euiccid": "9999999999999",
                "exFactoryILevel": "F056-18-11-531",
                "exFactoryPUStep": "1118",
                "headUnit": "ID5",
                "hmiVersion": "ID5",
                "iStep": "F056-20-11-545",
                "isLscSupported": true,
                "isMappingPending": false,
                "isMappingUnconfirmed": false,
                "model": "X1 sDrive20i",
                "puStep": "1120",
                "telematicsUnit": "ATM",
                "themeSpecs": {
                    "vehicleStatusBackgroundColor": {
                        "blue": 92,
                        "green": 89,
                        "red": 85
                    }
                },
                "vin": "ABCD1234",
                "year": 2019
            },
            "available_attributes": [
                "gps_position",
                "vin",
                "remaining_range_total",
                "mileage",
                "remaining_fuel",
                "remaining_range_fuel",
                "fuel_percent",
                "condition_based_services",
                "check_control_messages",
                "door_lock_state",
                "timestamp",
                "last_update_reason",
                "lids",
                "windows"
            ],
            "available_state_services": [
                "status"
            ],
            "brand": "bmw",
            "charging_profile": null,
            "drive_train": "COMBUSTION",
            "drive_train_attributes": [
                "remaining_range_total",
                "mileage",
                "remaining_fuel",
                "remaining_range_fuel",
                "fuel_percent"
            ],
            "has_hv_battery": false,
            "has_internal_combustion_engine": true,
            "has_range_extender": false,
            "has_weekly_planner_service": false,
            "is_vehicle_tracking_enabled": true,
            "lsc_type": "ACTIVATED",
            "name": "X1 sDrive20i",
            "observer_latitude": null,
            "observer_longitude": null
        }
    }

Happy to help if I can. I have not written an Indigo plugin before but I do know Python. Thanks

**Comment by FlyingDiver** [comment]
The state "all_lids_closed" is the status of the doors and hood/trunk.  "all_windows_closed" is the windows.  Also, "gps_heading".  Is there some reason you can't use these?

**Comment by FlyingDiver** [comment]
If you want access to data not currently in the states, you can write your own Python script to get it.  Here's an example.
```
#! /usr/bin/env python
# -*- coding: utf-8 -*-
####################

import json
import indigo

cd_plugin = indigo.server.getPlugin("com.flyingdiver.indigoplugin.bmw-cd")
if not cd_plugin.isEnabled():
    indigo.server.log(("Connected Drive Plugin not enabled")
    exit()
    
props = {
    'vin':"PUT YOUR VIN HERE" 
}
vehicle_json = cd_plugin.executeAction("fetchVehicleData", props=props, waitUntilDone=True)
indigo.server.log((f"Connected Drive Data for VIN {props['vin']}:\n{vehicle_json}")

vehicle_data = json.loads(vehicle_json)
indigo.server.log(f"Got data for {vehicle_data['vehicle']['attributes']['year']} {vehicle_data['vehicle']['attributes']['model']}")
```

**Comment by turribeach** [comment]
Well that defeats the purpose of having a plugin in Indigo since it will be easier for me to just use the underlying bimmer_connected package and call it directly. But I am happy to make changes myself and submit a PR once done.

**Comment by FlyingDiver** [comment]
Do you actually need the individual doors/windows?  The aggregate states are already there.

**Comment by FlyingDiver** [comment]
Please try https://github.com/FlyingDiver/Indigo-Connected-Drive/releases/tag/2022.1.0b1

**Comment by turribeach** [comment]
BTW I do use all_lids_closed and all_windows_closed, but either of these are false and the car is at home I sent an alert indicating what is open (ie Passenger Front Window is open) hence why I want to be able to get each of the windows, doors, hood, sunroof and trunk status. One time my trunk opened as I had the car keys in my pocket and they got pressed with another set of keys and my alert saved me from having the car trunk open overnight.

**Comment by FlyingDiver** [comment]
Well, you would have gotten the alert anyway, but it wouldn't have told you which lid was open.  ;)

I'll look at it again after this round is tested.  I just hate creating huge numbers of states.

**Comment by turribeach** [comment]
Yes although the handy thing is that sometimes it's not obvious what's open. Oftenly it will be a nearly closed window or door that's not closed properly but appears shut. And the BMW app doesn't tell which doors or windows are open.

**Comment by FlyingDiver** [comment]
Do you need a state for each lid/window, or would one that has a list of open ones work?  Then there's only two extra states.

**Comment by FlyingDiver** [comment]
<img width="397" alt="Screen Shot 2022-05-25 at 9 06 17 AM" src="https://user-images.githubusercontent.com/72976/170269525-2ae736ca-721b-4a1f-8d93-c45c344a5274.png">
