### ISSUE TITLE
get_account error

### ISSUE THREAD

**Issue by turribeach** [FlyingDiver/Indigo-Connected-Drive#16]
Got this after a few successful refreshes:

   Connected Drive Warning         BMW Connected Drive Account: get_account error: 

Obviously some error on calling the API but it will be good if we get a bit more info on the error? The plugin Event Logging Level is already at "Detailed Debugging Messages".

**Comment by turribeach** [comment]
Second failed update had more details, maybe slightly different failure point?

   Connected Drive Warning         BMW Connected Drive Account: get_account error: Server error '502 Bad Gateway' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1653424099910&tireGuardMode=ENABLED'
For more information check: https://httpstatuses.com/502

**Comment by FlyingDiver** [comment]
Do you have the region set correctly?

**Comment by FlyingDiver** [comment]
How fast are you trying to refresh?

**Comment by turribeach** [comment]
Yes region is set fine, I think their API is down. I am refreshing every 5 mins, had it set like that for ages.

**Comment by FlyingDiver** [comment]
Not sure what I can do differently here.  I'm catching the exception and printing the error to the log.
