### ISSUE TITLE
Implement Geofencing alerts 

### ISSUE THREAD

**Issue by turribeach** [FlyingDiver/Indigo-Connected-Drive#18]
So here is how I use this plugin and you may want to incorporate to the plugin. I have a trigger that runs every time the car updates. It then checks if the car is at home. If the car is "at home" it then checks to see if the car has any open doors, windows or lids. If so it will send an alert after a defined set time. 

Below are the parameters of the script, which should give you an idea how it works:

    home_lat = 59.99999             # Your home latitude, get it from Google maps by clicking on your house
    home_log = 0.99999              # Your home longitude, get it from Google maps by clicking on your house
    car_device_id = 1004901346       # Device ID of the vehicle you created with the Connected Drive plugin 
    geo_distance_unit = "kilometers" # kilometers or miles
    geo_fence_distance = 0.1         # How big you want the geofence to be for your car to be considered at home in kilometers
    wait_minutes_before_alert = 20   # How many minutes to wait before sending an alert
    repeat_alerts = True             # Set to false to not receive the same alert repeatedly every time the Connected Drive plugin     refreshes the data
    variables_folder_id = 916264876  # Folder ID where you want the variables that this script uses to be created
    utc_time_zone = tz.gettz('UTC')  # Time Zone of BMW response
    local_time_zone = tz.gettz('Europe/London') # Local Time Zone 

I coded this my left left the car open a couple of times and we had few things stolen from the car by oportunistic thieves. Few times as well the boot got opened by mistake as I had the car keys in my pocket with other keys.

**Comment by FlyingDiver** [comment]
Is home also the location of the Indigo server?

**Comment by turribeach** [comment]
Yes.

**Comment by FlyingDiver** [comment]
Distance from Indigo server location calculated in km in next release.
