### ISSUE TITLE
Secured status no longer available

### ISSUE THREAD

**Issue by turribeach** [FlyingDiver/Indigo-Connected-Drive#19]
So in the old version of the plugin (before the bimmer_connected update and the Indigo 2022 update) the door_lock_state would return either LOCKED or SECURED. Secured was returned when the car was locked and the alarm was activated. Locked was returned when the car was locked but the alarm was not activated. You can press the lock button again after locking to disable the interior alarm if you are leaving an animal inside the car. Also if you forgot to lock the car and do a remote lock from the BMW app the car will be locked but not alarmed. Is there any way to show this state back? 

I just used the bimmer_connected package and test the vehicle output with the car LOCKED and the car SECURED and I don't see any difference. The BWM app doesn't show a difference either, it's says Locked for both scenarios, whether the car alarm is active or not. Any ideas what happened with the secured state?

**Comment by FlyingDiver** [comment]
Not a clue.  Since the app doesn't show a difference, I would guess they removed it.

**Comment by turribeach** [comment]
OK I will raise on the bimmer_connected repo and see if they know. I just looked at the output I saved a while ago and it def had SECURED in it.

**Comment by FlyingDiver** [comment]
It's still in the API:
https://bimmer-connected.readthedocs.io/en/latest/module/vehicle.html#bimmer_connected.vehicle.doors_windows.LockState

**Comment by turribeach** [comment]
Thanks, I will ask them as it seems to be returning LOCKED for both states now.

**Comment by FlyingDiver** [comment]
Yeah, that shows it's a valid return state, but it's not getting returned.  So either the library broke something, or MyBMW stopped sending it.
