### ISSUE TITLE
Set destination remotely

### ISSUE THREAD

**Issue by ryanbuckner** [FlyingDiver/Indigo-Connected-Drive#22]
Is there a way to send destination or trips to the car through Python like there is in the app?  The app is missing the feature to schedule or create reoccurring trips, like most people have in their routines.  

This could be solved through Indigo with that enhancement if it's possible.

**Comment by FlyingDiver** [comment]
Looks like it's possible to send a POI to the vehicle, but it's not currently implemented.

**Comment by ryanbuckner** [comment]
> Looks like it's possible to send a POI to the vehicle, but it's not currently implemented.

Is that an enhancement request here or in the Git for the underlying library?

**Comment by FlyingDiver** [comment]
For the plugin.  The library has the method implemented, no idea if it actually works.

**Comment by ryanbuckner** [comment]
I'm using the POI command line using a shortcut. Seems to work.

**Comment by FlyingDiver** [comment]
Code implemented, but failing for me.  Might be an account issue, as I get the same result with the cli tool.

**Comment by ryanbuckner** [comment]
It used to work for me through the CLI and now I get an authorization error.

**Comment by FlyingDiver** [comment]
https://github.com/FlyingDiver/Indigo-Connected-Drive/releases/tag/2024.0.1

**Comment by ryanbuckner** [comment]
Tried the POI and got this error: 
Nov 25, 2024 at 3:47:24 PM
   Action Group                    BMW -  Send POI
   Connected Drive Warning         XXXXXXXXXXXX55588: sendCommandAction send_poi error: HTTPStatusError: Bad Request - 

I think the structure of the POI CLI is very fickle.

<img width="581" alt="image" src="https://github.com/user-attachments/assets/712abfa7-e1dd-4f89-9757-360af59ed84b">

**Comment by FlyingDiver** [comment]
Yeah that’s about what I got too but I have no idea what I did wrong. Have you used the command line tool that’s included in the library?

**Comment by FlyingDiver** [comment]
You should be able to run the latest cli tool once with a new captcha token, then run it subsequent times without, since it caches the refresh token.

**Comment by ryanbuckner** [comment]
The shortcut just takes the address from my clipboard and determines lat long, then sends the command in terminal.  Ryan ***@***.*** Nov 25, 2024, at 4:48 PM, Joe Keenan ***@***.***> wrote:﻿
Not sure how doing it in a shortcut affects that. I could not get it to work, but I didn't spend much time on it.

**Comment by ryanbuckner** [comment]
added the captcha. Errors: 

MyBMWAuthError due to HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)
MyBMWAuthError: HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)

**Comment by FlyingDiver** [comment]
My experience with the command line tool is that it's very picky about operation order. I'm not at home now so I can't look at my terminal history. 

Try with a simple status command first until you get that working, then try the send poi command.

**Comment by ryanbuckner** [comment]
I’m using the status command.  No luck so far but I’m looking at the docs and I know I have the order right.  I think I may need a different captcha token since I’m on a different computer Ryan ***@***.*** Nov 25, 2024, at 6:42 PM, Joe Keenan ***@***.***> wrote:﻿
My experience with the command line tool is that it's very picky about operation order. I'm not at home now so I can't look at my terminal history.
Try with a simple status command first until you get that working, then try the send poi command.

**Comment by FlyingDiver** [comment]
Each captcha token is only usable once. Any new authorization needs a new captcha token.

**Comment by ryanbuckner** [comment]
I grabbed a new one. Same error

**Comment by turribeach** [comment]
There is something going on with the CLI. [I started a discussion](https://github.com/bimmerconnected/bimmer_connected/discussions/681) on the bimmer_connectedrepo. I was able to get it to work after 30 tries. It could be that the captcha is very short lived. But I can't say for sure since the CLI caches the authentication so after I got it working it basically ignores any new captchas. Try to do it as quickly as possible.

**Comment by FlyingDiver** [comment]
Monitoring https://github.com/bimmerconnected/bimmer_connected/issues/684

Disabling send_poi in release build for now.

**Comment by ryanbuckner** [comment]
This appears to have fixed it. Thanks!

**Comment by ryanbuckner** [comment]
This is working. I'm going to close it.
