### ISSUE TITLE
'403 Quota Exceeded' error

### ISSUE THREAD

**Issue by ryanbuckner** [FlyingDiver/Indigo-Connected-Drive#23]
I restarted my Indigo Server on 5/17 to install a new UPS.  Since then, the device config for my car has lost it's vehicle options and I'm receiving a '403 Quota Exceeded' error. I'm unable to configure the device to add the car. 

Is anyone else experiencing this?  I saw that it was a problem in Sept 2022 for a while

Version: Connected Drive 2022.1.1

`Connected Drive Warning         BMW 540 Account : get_account error: Client error '403 Quota Exceeded' for url 'https://cocoapi.bmwgroup.us/eadrax-vcs/v2/vehicles'
For more information check: https://httpstatuses.com/403`

**Comment by turribeach** [comment]
Working fine for me. I think once you exceed your quote you need to let it cool for a while to reset. Disable the plugin and try tomorrow. I am using update frequency = 25mins and that gets me without errors.

**Comment by FlyingDiver** [comment]
That's not a plugin problem.  Except maybe I could trap the error and disable polling servers for a while.  Not sure if that's any better, as it's just masking the issue.
