### ISSUE TITLE
Date/time on Indigo don't match library

### ISSUE THREAD

**Issue by turribeach** [FlyingDiver/Indigo-Connected-Drive#25]
In Indigo my BMW device has Last Update 2023-06-21 21:37:20 and in the properties I have:

last_update = 21 Jun 2023 21:37:20 BST
timestamp = 21 Jun 2023 21:37:20 BST

I ran a fingerprint using bimmer_connected around the same time and I got this:

        "lastFetched": "2023-06-21T20:37:16.134Z",
        "lastUpdatedAt": "2023-06-21T20:11:40Z",

Last fetched matches the date/time above, save for the time zone conversion. Where can I see the lastUpdatedAt in Indigo?

Thanks

**Comment by FlyingDiver** [comment]
I do not know where that script is getting that value from.  Next time I'm in the code I'll take a look.  Not sure when I'll be working on this plugin again.
