### ISSUE TITLE
Error on account connection

### ISSUE THREAD

**Issue by damiang1** [FlyingDiver/Indigo-Connected-Drive#27]
Latest plugin yields this in Indigo Log.  Using same login info as myBMW app.   

Connected Drive Warning         new device: get_account error: Client error '422 Forbidden' for url 'https://cocoapi.bmwgroup.us/eadrax-ucs/v1/presentation/oauth/config'
For more information check: https://httpstatuses.com/422

**Comment by turribeach** [comment]
Working fine for me, must be something at your side...

**Comment by damiang1** [comment]
Tried everything, cant possible see what is wrong.  Perhaps there is a newer library I need to install other than pip3.10 install bimmer_connected==0.9.0 aiohttp httpx. It appears I am "logging on" but cant resolve and find the vehicle.
 This is the error I get...
Connected Drive                 Starting Connected Drive
   Connected Drive                 new device: Starting cdAccount Device
   Connected Drive Warning         new device: get_account error: Client error '422 Forbidden' for url 'https://cocoapi.bmwgroup.us/eadrax-ucs/v1/presentation/oauth/config'
For more information check: https://httpstatuses.com/422
   Connected Drive                 new device: 0 vehicles found.

**Comment by FlyingDiver** [comment]
You sure you have the right region?

**Comment by damiang1** [comment]
Yes USA.  I just cant get to work from a year ago

**Comment by ryanbuckner** [comment]
bimmer_connected is at version .0.14.0

**Comment by damiang1** [comment]
Didnt realize that.  I did this in terminal and ALL IS FINE!  pip3.10 install bimmer_connected==0.14.0 aiohttp httpx.  Thank you!

**Comment by FlyingDiver** [comment]
I've put in code to check the version and throw an error if it's not 0.14.0, it'll be in the next release.  I have a number of issues for this plugin I need to chase down.
