### ISSUE TITLE
'NoneType' object has no attribute 'longitude'

### ISSUE THREAD

**Issue by ryanbuckner** [FlyingDiver/Indigo-Connected-Drive#28]
Just started getting this error each polling period. 

Could be related to this, but I haven't made any changes. 

`"is_vehicle_tracking_enabled": false,`

   ```
Reloading plugin "Connected Drive 2022.1.1" using API v3.1
   Stopping plugin "Connected Drive 2022.1.1" (pid 60276)
   Stopped plugin "Connected Drive 2022.1.1"
   Starting plugin "Connected Drive 2022.1.1" (pid 93760)
   Started plugin "Connected Drive 2022.1.1"
   Connected Drive Error           Error in plugin execution runConcurrentThread:

  File "plugin.py", line 166, in runConcurrentThread
  File "plugin.py", line 220, in _do_update
type: 'NoneType' object has no attribute 'longitude'

   Connected Drive Error           plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

```

**Comment by FlyingDiver** [comment]
Turn on debug logging and restart the plugin, then post log up to error.

**Comment by ryanbuckner** [comment]
I think the subscription ran out.

**Comment by ryanbuckner** [comment]
Upon renewing my subscription, the option to enable vehicle tracking is no longer there.  Maybe it will take a few hours. I'll check back.

**Comment by ryanbuckner** [comment]
US. Requires $120 every year . Apparently things don't work for a few hours
after updating the subscription.

**Comment by turribeach** [comment]
Typical BMW, so out of date on their technology stack!

**Comment by FlyingDiver** [comment]
So is it working again?

I should do a better job of trapping that error, so don't close this issue until I fix that.

**Comment by ryanbuckner** [comment]
Not yet. Some have reported it taking as much as 24 hours to show up in
iDrive as an option for Vehicle Tracking

**Comment by ryanbuckner** [comment]
Vehicle Tracking is back Ryan ***@***.*** Oct 5, 2023, at 2:46 PM, Ryan Buckner ***@***.***> wrote:﻿Not yet. Some have reported it taking as much as 24 hours to show up in iDrive as an option for Vehicle TrackingOn Thu, Oct 5, 2023 at 2:28 PM Joe Keenan ***@***.***> wrote:
So is it working again?
I should do a better job of trapping that error, so don't close this issue until I fix that.

**Comment by FlyingDiver** [comment]
Error trapping already in my current code, just not pushed yet.
