### ISSUE TITLE
Nonetype error on plugin load, object has no attribute‘latitude’

### ISSUE THREAD

**Issue by hensed** [FlyingDiver/Indigo-Connected-Drive#29]
Loading plugin "Connected Drive 2023.2.0" using API v3.1
   Starting plugin "Connected Drive 2023.2.0" (pid 18759)
   Started plugin "Connected Drive 2023.2.0"
   Connected Drive                 Starting Connected Drive
   Connected Drive                 BMW Connected Drive Account: Starting cdAccount Device
   Connected Drive                 BMW Connected Drive Account: 1 vehicles found.
   Connected Drive                 BMW M6: Starting cdVehicle Device
   Connected Drive Error           Error in plugin execution runConcurrentThread:

  File "plugin.py", line 165, in runConcurrentThread
  File "plugin.py", line 242, in _do_update
type: 'NoneType' object has no attribute 'latitude'

   Connected Drive Error           plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by FlyingDiver** [comment]
Same as #28, fixed in next release.
