### ISSUE TITLE
Indigo UI state = "LockState.UNLOCKED"

### ISSUE THREAD

**Issue by ryanbuckner** [FlyingDiver/Indigo-Connected-Drive#30]
In the previous version, the UI state showed "UNLOCKED" and the latest update changed that to "LockState.UNLOCKED".  I don't think it affects functionality but in case it's an unintended mistake I wanted to report it. 

<img width="691" alt="lockstate" src="https://github.com/FlyingDiver/Indigo-Connected-Drive/assets/1781929/e1be6548-d6fd-434b-8592-4a34b8ce6971">

**Comment by FlyingDiver** [comment]
I did not make any changes that could effect that state.

Is it possible this change actually came from an Indigo update?

**Comment by FlyingDiver** [comment]
Or maybe it's a Python string formatting change.  Here's the code that sets that, and it hasn't changed since I implemented that state value option.

```
                case 'door_lock_state':
                    status_value = vehicle.doors_and_windows.door_lock_state
                    status_ui = f"{vehicle.doors_and_windows.door_lock_state}"```

**Comment by FlyingDiver** [comment]
I'm seeing the "UNLOCKED" value in the state now, so I don't know what would have caused this.

**Comment by FlyingDiver** [comment]
Fixed in next release.
